language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2

sudo: false

dist: precise

notifications:
  recipients:
    - memde@engineyard.com
    - srosenfeld@engineyard.com
  webhooks:
    urls:
    - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true

before_install:
  - sudo rm -f /opt/jdk_switcher/jdk_switcher.sh
